---
- name: Register faas-cli version
  command: /usr/local/bin/faas-cli version --short-version
  register: faascli_version
  ignore_errors: true
  changed_when: no

- name: Download faas-cli install script
  get_url:
    url: "{{ openfaas_cli_script_url }}"
    dest: "{{ openfaas_cli_script_path }}"
    mode: 0755
  when: faascli_version is failed
  register: faascli_installer_download

- name: Execute faas-cli install script
  command: "{{ openfaas_cli_script_path }}"
  become: true
  when: faascli_installer_download is succeeded and faascli_installer_download is not skipped

- name: Remove faas-cli install script
  file:
    path: "{{ openfaas_cli_script_path }}"
    state: absent
  when: faascli_installer_download is succeeded and faascli_installer_download is not skipped

- name: Get faas
  git:
    repo: "{{ openfaas_repo_url }}"
    dest: "{{ openfaas_path }}"
    version: "{{ openfaas_version }}"

- name: Deploy faas
  command: ./deploy_stack.sh
  args:
    chdir: "{{ openfaas_path }}"
  changed_when: no
  register: faas

- debug: msg="{{ faas.stdout }}"
